<?php

return [
    'web' => [
        'home' => [
            'pagetitle' => 'Home',
            'longtitle' => '',
            'template' => 1,
            'alias' => 'index',
            'hidemenu' => true,
            'richtext' => 1,
        ],
        'service' => [
            'pagetitle' => 'Service pages',
            'template' => 0,
            'hidemenu' => true,
            'published' => false,
            'alias_visible' => false,
            'resources' => [
                '403' => [
                    'pagetitle' => '403',
                    'longtitle' => 'Access is denied',
                    'template' => 0,
                    'hidemenu' => true,
                    'uri' => '403',
                    'uri_override' => true,
                    'richtext' => 1,
                ],
                '404' => [
                    'pagetitle' => '404',
                    'longtitle' => '404 error | Page not found',
                    'template' => 2,
                    'hidemenu' => true,
                    'uri' => '404',
                    'uri_override' => true,
                    'richtext' => 1,
                ],
                '503' => [
                    'pagetitle' => '503',
                    'longtitle' => 'Site unavailable',
                    'template' => 0,
                    'hidemenu' => true,
                    'uri' => '503',
                    'uri_override' => true,
                    'richtext' => 1,
                ],
                'sitemap_html' => [
                    'pagetitle' => 'Site map',
                    'alias' => 'sitemap',
                    'template' => 0,
                    'hidemenu' => true,
                    'uri' => 'sitemap',
                    'uri_override' => true,
                ],
                'sitemap_xml' => [
                    'pagetitle' => 'SiteMap',
                    'alias' => 'sitemap.xml',
                    'template' => 0,
                    'hidemenu' => true,
                    'uri' => 'sitemap.xml',
                    'uri_override' => true,
                    'content_type' => 2,
                ],
                'policy' => [
                    'pagetitle' => 'Privacy Policy',
                    'longtitle' => '',
                    'template' => 2,
                    'alias' => 'policy',
                    'hidemenu' => true,
                    'uri' => 'policy',
                    'uri_override' => true,
                    'richtext' => 1,
                ],
            ],
        ],
    ],
];